# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2018

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Archives:
    widget: Archives
    link: /archives
  Posts:
    name: posts # category name
    widget: Posts
    link: /categories/posts
  Tags:
    widget: Tags
    link: /tags

#other menu1
# otherMenu1: Search
#other Menu2
otherMenu2:
  About: /about

# menu
archive_type: 'yearly'
tag_type: 'monthly'
show_count: false

# 是否开启toc
# toc: true
toc:
  list_number: true  # 是否显示数字排序
#Tag 页面的标题
tagTitle: Tags

# A sentense to show
signature: 是非曲直谁堪断    乾坤诸相冷眼观    芸芸百态诉笔墨    留与后人付笑谈

theme:
  color: Default
  fancybox: false
excerpt_link: 更多

favicon: /img/favicon.ico

# ===========================================
# Version
# ===========================================
version: 1.1
